name: Windows e2e

on:
  workflow_run:
    workflows: [Build Windows installer]
    types:
      - completed
  
jobs:
  windows:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        windows-version: ['11']
        windows-featurepack: ['23h2-ent']
    
    steps:

      - name: Download GH context  
        id: download-gh-context-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: gh_context

      - name: Create e2e results
        id: create-e2e-results
        run: |
          AFTER=$(cat gh_context.json | jq -r '.event.after')
          echo "SHA_ID=${AFTER}" >> "$GITHUB_ENV"
          cat > e2e-results.xml << EOF
          <?xml version="1.0" encoding="utf-8"?>
          <INTRO>
          <title>pass/fail</title>
          </INTRO>
          EOF

      - name: Upload Artifact
        id: upload-e2e-results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: "results-${{env.SHA_ID}}"
          path: |
            **/e2e-results.xml